export const INITIAL_TENANTS = [
  {
    id: 'tenant-gents-101',
    name: 'SHAAN Gents Cloth House',
    tagline: 'Premium Unstitched Men Fabrics & Latha',
    city: 'Azam Cloth Market, Lahore',
    address: 'Shop #14, Gate #3, Azam Market, Lahore, Pakistan',
    phone: '+92 300 4567890',
    shopType: 'gents_unstitched', // 'gents_unstitched' | 'ladies_fashion' | 'ready_made_apparel' | 'mixed_garments'
    ownerName: 'Haji Muhammad Ahmed',
    modules: {
      unstitched_fabric: true,
      ready_made_apparel: false,
      vendor_ledger: true,
      promotional_engine: true,
      analytics: true,
    },
    status: 'active',
    createdAt: '2026-06-01',
  },
  {
    id: 'tenant-ladies-102',
    name: 'Gulberg Ladies Pret & Lawn Outlet',
    tagline: 'Exclusive Designer 3-Piece & Silk Collections',
    city: 'Gulberg III, Lahore',
    address: 'Shop #8, MM Alam Road, Gulberg III, Lahore, Pakistan',
    phone: '+92 321 8899001',
    shopType: 'ladies_fashion',
    ownerName: 'Haji Muhammad Ahmed', // Multi-shop owner!
    modules: {
      unstitched_fabric: true,
      ready_made_apparel: true,
      vendor_ledger: true,
      promotional_engine: true,
      analytics: true,
    },
    status: 'active',
    createdAt: '2026-07-15',
  },
  {
    id: 'tenant-apparel-103',
    name: 'Royal Threads Shirts & Trousers Hub',
    tagline: 'Ready-Made Formal Shirts, Chinos & Denim Pants',
    city: 'Tariq Road, Karachi',
    address: 'Plot #45, Commercial Area, Tariq Road, Karachi, Pakistan',
    phone: '+92 333 7766554',
    shopType: 'ready_made_apparel',
    ownerName: 'Chaudhry Rashid Tariq',
    modules: {
      unstitched_fabric: false,
      ready_made_apparel: true,
      vendor_ledger: true,
      promotional_engine: true,
      analytics: true,
    },
    status: 'active',
    createdAt: '2026-08-01',
  },
];

export const INITIAL_PRODUCTS = [
  // TENANT 1: SHAAN GENTS CLOTH HOUSE (Gents Unstitched)
  {
    id: 'prod-101',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched', // 'unstitched' | 'apparel'
    barcode: 'PAK-LAW-880101',
    fabricType: 'Lawn',
    fabricMaterial: 'Gul Ahmed Premium Printed Lawn (3-Piece)',
    fabricColor: 'Emerald Mint & Floral',
    wholesalePrice: 1850,
    retailPrice: 4200,
    initialStock: 50,
    stock: 35,
    reorderLimit: 10,
    unitType: 'Suit',
    vendorId: 'ven-1',
  },
  {
    id: 'prod-102',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched',
    barcode: 'PAK-COT-880102',
    fabricType: 'Cotton',
    fabricMaterial: 'Pasha Superfine Latha White Bolt',
    fabricColor: 'Crisp Bleached White',
    wholesalePrice: 450,
    retailPrice: 950,
    initialStock: 120,
    stock: 85.5,
    reorderLimit: 25,
    unitType: 'Meter',
    vendorId: 'ven-2',
  },
  {
    id: 'prod-103',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched',
    barcode: 'PAK-BOX-880103',
    fabricType: 'Jacquard',
    fabricMaterial: 'J. Junaid Jamshed Jacquard Gift Box Set',
    fabricColor: 'Royal Sapphire Navy',
    wholesalePrice: 3200,
    retailPrice: 6800,
    initialStock: 30,
    stock: 18,
    reorderLimit: 5,
    unitType: 'Box',
    vendorId: 'ven-3',
  },
  {
    id: 'prod-104',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched',
    barcode: 'PAK-WNW-880104',
    fabricType: 'Wash & Wear',
    fabricMaterial: 'Grace Fine Wash & Wear Gents Unstitched',
    fabricColor: 'Charcoal Slate Gray',
    wholesalePrice: 2100,
    retailPrice: 4800,
    initialStock: 40,
    stock: 26,
    reorderLimit: 8,
    unitType: 'Suit',
    vendorId: 'ven-1',
  },
  {
    id: 'prod-105',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched',
    barcode: 'PAK-KHD-880105',
    fabricType: 'Khaddar',
    fabricMaterial: 'Kamalia Handloom Pure Khaddar',
    fabricColor: 'Rustic Ochre Brown',
    wholesalePrice: 1450,
    retailPrice: 3400,
    initialStock: 45,
    stock: 12,
    reorderLimit: 10,
    unitType: 'Suit',
    vendorId: 'ven-3',
  },

  // TENANT 2: GULBERG LADIES PRET & LAWN (Ladies Fashion)
  {
    id: 'prod-201',
    tenantId: 'tenant-ladies-102',
    productType: 'unstitched',
    barcode: 'LAD-SLK-770201',
    fabricType: 'Silk',
    fabricMaterial: 'Bareeze Pure Raw Silk Embroidered 3-Piece',
    fabricColor: 'Deep Crimson Red',
    wholesalePrice: 4200,
    retailPrice: 9500,
    initialStock: 40,
    stock: 28,
    reorderLimit: 8,
    unitType: 'Suit',
    vendorId: 'ven-2',
  },
  {
    id: 'prod-202',
    tenantId: 'tenant-ladies-102',
    productType: 'unstitched',
    barcode: 'LAD-CHF-770202',
    fabricType: 'Chiffon',
    fabricMaterial: 'Al-Karam Luxury Party Chiffon Collection',
    fabricColor: 'Pastel Rose Dust',
    wholesalePrice: 5500,
    retailPrice: 12500,
    initialStock: 25,
    stock: 14,
    reorderLimit: 5,
    unitType: 'Suit',
    vendorId: 'ven-1',
  },
  {
    id: 'prod-203',
    tenantId: 'tenant-ladies-102',
    productType: 'unstitched',
    barcode: 'LAD-VLV-770203',
    fabricType: 'Velvet',
    fabricMaterial: 'Sitara Micro-Velvet 9000 Shawl Suit',
    fabricColor: 'Royal Plum Purple',
    wholesalePrice: 3800,
    retailPrice: 8200,
    initialStock: 30,
    stock: 19,
    reorderLimit: 6,
    unitType: 'Suit',
    vendorId: 'ven-3',
  },

  // TENANT 3: ROYAL THREADS SHIRTS & TROUSERS (Ready-Made Apparel with Variant Grid)
  {
    id: 'prod-301',
    tenantId: 'tenant-apparel-103',
    productType: 'apparel',
    barcode: 'APP-SHT-550301',
    fabricType: 'Apparel',
    apparelCategory: 'Formal Shirt',
    fabricMaterial: 'Royal Cotton Oxford Slim-Fit Formal Shirt',
    fabricColor: 'Sky Blue & White',
    wholesalePrice: 1200,
    retailPrice: 2800,
    initialStock: 80,
    stock: 64,
    reorderLimit: 15,
    unitType: 'Piece',
    vendorId: 'ven-2',
    hasVariants: true,
    variants: [
      { id: 'var-301-1', sku: 'SHT-BLU-S', size: 'S (38)', color: 'Sky Blue', stock: 12, retailPrice: 2800, wholesalePrice: 1200 },
      { id: 'var-301-2', sku: 'SHT-BLU-M', size: 'M (40)', color: 'Sky Blue', stock: 18, retailPrice: 2800, wholesalePrice: 1200 },
      { id: 'var-301-3', sku: 'SHT-BLU-L', size: 'L (42)', color: 'Sky Blue', stock: 20, retailPrice: 2800, wholesalePrice: 1200 },
      { id: 'var-301-4', sku: 'SHT-BLU-XL', size: 'XL (44)', color: 'Sky Blue', stock: 14, retailPrice: 2800, wholesalePrice: 1200 },
    ],
  },
  {
    id: 'prod-302',
    tenantId: 'tenant-apparel-103',
    productType: 'apparel',
    barcode: 'APP-TRS-550302',
    fabricType: 'Apparel',
    apparelCategory: 'Dress Trouser',
    fabricMaterial: 'Executive Stretch Cotton Chino Trouser',
    fabricColor: 'Khaki Beige',
    wholesalePrice: 1400,
    retailPrice: 3200,
    initialStock: 70,
    stock: 52,
    reorderLimit: 12,
    unitType: 'Piece',
    vendorId: 'ven-3',
    hasVariants: true,
    variants: [
      { id: 'var-302-1', sku: 'TRS-KHK-30', size: 'W30 L32', color: 'Khaki Beige', stock: 10, retailPrice: 3200, wholesalePrice: 1400 },
      { id: 'var-302-2', sku: 'TRS-KHK-32', size: 'W32 L32', color: 'Khaki Beige', stock: 16, retailPrice: 3200, wholesalePrice: 1400 },
      { id: 'var-302-3', sku: 'TRS-KHK-34', size: 'W34 L32', color: 'Khaki Beige', stock: 18, retailPrice: 3200, wholesalePrice: 1400 },
      { id: 'var-302-4', sku: 'TRS-KHK-36', size: 'W36 L32', color: 'Khaki Beige', stock: 8, retailPrice: 3200, wholesalePrice: 1400 },
    ],
  },
  {
    id: 'prod-303',
    tenantId: 'tenant-apparel-103',
    productType: 'apparel',
    barcode: 'APP-PNT-550303',
    fabricType: 'Apparel',
    apparelCategory: 'Denim Jeans',
    fabricMaterial: 'Urban Raw Selvedge Slim Denim Jeans',
    fabricColor: 'Midnight Dark Indigo',
    wholesalePrice: 1600,
    retailPrice: 3900,
    initialStock: 50,
    stock: 36,
    reorderLimit: 10,
    unitType: 'Piece',
    vendorId: 'ven-1',
    hasVariants: true,
    variants: [
      { id: 'var-303-1', sku: 'JNS-IND-30', size: 'W30', color: 'Dark Indigo', stock: 8, retailPrice: 3900, wholesalePrice: 1600 },
      { id: 'var-303-2', sku: 'JNS-IND-32', size: 'W32', color: 'Dark Indigo', stock: 14, retailPrice: 3900, wholesalePrice: 1600 },
      { id: 'var-303-3', sku: 'JNS-IND-34', size: 'W34', color: 'Dark Indigo', stock: 10, retailPrice: 3900, wholesalePrice: 1600 },
      { id: 'var-303-4', sku: 'JNS-IND-36', size: 'W36', color: 'Dark Indigo', stock: 4, retailPrice: 3900, wholesalePrice: 1600 },
    ],
  },
];

export const INITIAL_ROLES = [
  {
    id: 'role-superadmin',
    roleName: 'Super Admin',
    description: 'Master platform administrator with authority to onboard tenants, manage subscriptions, and oversee all shop databases.',
    permissions: [
      'super_admin',
      'make_sale',
      'product_setup',
      'check_stock',
      'stock_updation',
      'vendor_ledger',
      'discounts',
      'analytics',
      'settings',
    ],
    isSystem: true,
  },
  {
    id: 'role-admin',
    roleName: 'Admin',
    description: 'Shop owner / Branch Administrator with full access to this specific shop terminal and ledgers.',
    permissions: [
      'make_sale',
      'product_setup',
      'check_stock',
      'stock_updation',
      'vendor_ledger',
      'discounts',
      'analytics',
      'settings',
    ],
    isSystem: true,
  },
  {
    id: 'role-manager',
    roleName: 'Store Manager',
    description: 'Manages sales, stock restocks, vendor payments, and promotional discounts.',
    permissions: [
      'make_sale',
      'product_setup',
      'check_stock',
      'stock_updation',
      'vendor_ledger',
      'discounts',
      'analytics',
    ],
    isSystem: false,
  },
  {
    id: 'role-salesman',
    roleName: 'Salesman',
    description: 'Front-desk POS checkout, stock lookup, and quick item search access.',
    permissions: ['make_sale', 'check_stock'],
    isSystem: true,
  },
  {
    id: 'role-clerk',
    roleName: 'Inventory Clerk',
    description: 'Handles product setup, barcode printing, restocks, and damage logging.',
    permissions: ['product_setup', 'check_stock', 'stock_updation'],
    isSystem: false,
  },
];

export const INITIAL_USERS = [
  // SUPER ADMIN (Platform Master)
  {
    id: 'u-super',
    username: 'superadmin',
    password: '123',
    fullName: 'Engr. Zeeshan (Platform Super Admin)',
    role: 'Super Admin',
    tenantIds: ['tenant-gents-101', 'tenant-ladies-102', 'tenant-apparel-103'],
    isSuperAdmin: true,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
  },

  // MULTI-SHOP OWNER (Owns Gents + Ladies Shops)
  {
    id: 'u-1',
    username: 'ahmed_owner',
    password: '123',
    fullName: 'Haji Muhammad Ahmed',
    role: 'Admin',
    tenantIds: ['tenant-gents-101', 'tenant-ladies-102'], // Multi-Shop Owner!
    isSuperAdmin: false,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
  },

  // GENTS SHOP SALESMAN
  {
    id: 'u-2',
    username: 'tariq_gents',
    password: '123',
    fullName: 'Tariq Mahmood (Gents POS)',
    role: 'Salesman',
    tenantIds: ['tenant-gents-101'],
    isSuperAdmin: false,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
  },

  // LADIES SHOP SALESMAN
  {
    id: 'u-3',
    username: 'usman_ladies',
    password: '123',
    fullName: 'Usman Ghani (Ladies Pret)',
    role: 'Salesman',
    tenantIds: ['tenant-ladies-102'],
    isSuperAdmin: false,
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
  },

  // APPAREL SHOP CASHIER
  {
    id: 'u-4',
    username: 'rashid_apparel',
    password: '123',
    fullName: 'Rashid Tariq (Apparel POS)',
    role: 'Admin',
    tenantIds: ['tenant-apparel-103'],
    isSuperAdmin: false,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
  },
];

export const INITIAL_VENDORS = [
  {
    id: 'ven-1',
    tenantId: 'tenant-gents-101',
    vendorName: 'Gul Ahmed Textiles Wholesalers',
    contactPerson: 'Haji Farooq Gul',
    phone: '+92 321 9876543',
    city: 'Karachi, Pakistan',
    address: 'Site Industrial Area, Karachi',
    totalInvoiced: 450000,
    totalPaid: 320000,
    payments: [
      {
        id: 'pay-101',
        dateTime: '2026-07-20 11:30',
        dueDate: '2026-08-15',
        amountPaid: 200000,
        paymentMethod: 'Bank Transfer',
        referenceNote: 'Advance payment for winter lawn lot #4',
        loggedBy: 'Haji Muhammad Ahmed',
      },
    ],
    shipments: [
      {
        id: 'shp-101',
        dateTime: '2026-07-18 10:00',
        barcode: 'PAK-LAW-880101',
        itemName: 'Gul Ahmed Premium Printed Lawn (3-Piece)',
        qty: 50,
        unitType: 'Suit',
        invoiceTotal: 92500,
      },
    ],
  },
  {
    id: 'ven-2',
    tenantId: 'tenant-gents-101',
    vendorName: 'Pasha Fabrics Mill Agency',
    contactPerson: 'Malik Zafar Pasha',
    phone: '+92 300 5544332',
    city: 'Faisalabad, Pakistan',
    address: 'Cloth Market Road, Faisalabad',
    totalInvoiced: 280000,
    totalPaid: 210000,
    payments: [
      {
        id: 'pay-201',
        dateTime: '2026-07-25 15:45',
        dueDate: '2026-08-20',
        amountPaid: 210000,
        paymentMethod: 'Cash',
        referenceNote: 'Full cash payment for Latha cotton rolls',
        loggedBy: 'Haji Muhammad Ahmed',
      },
    ],
    shipments: [
      {
        id: 'shp-201',
        dateTime: '2026-07-24 12:00',
        barcode: 'PAK-COT-880102',
        itemName: 'Pasha Superfine Latha White Bolt',
        qty: 120,
        unitType: 'Meter',
        invoiceTotal: 54000,
      },
    ],
  },
  {
    id: 'ven-3',
    tenantId: 'tenant-apparel-103',
    vendorName: 'Denim & Garments Manufacturing Ltd',
    contactPerson: 'Khurram Shehzad',
    phone: '+92 333 4455667',
    city: 'Korangi Industrial Area, Karachi',
    address: 'Sector 15, Korangi, Karachi',
    totalInvoiced: 520000,
    totalPaid: 400000,
    payments: [
      {
        id: 'pay-301',
        dateTime: '2026-08-10 12:00',
        dueDate: '2026-08-30',
        amountPaid: 400000,
        paymentMethod: 'Bank Transfer',
        referenceNote: 'Settlement for Chino trousers lot #12',
        loggedBy: 'Rashid Tariq',
      },
    ],
    shipments: [
      {
        id: 'shp-301',
        dateTime: '2026-08-08 14:30',
        barcode: 'APP-TRS-550302',
        itemName: 'Executive Stretch Cotton Chino Trouser',
        qty: 70,
        unitType: 'Piece',
        invoiceTotal: 98000,
      },
    ],
  },
];

export const INITIAL_PROMOTIONAL_DISCOUNTS = [
  {
    id: 'disc-101',
    tenantId: 'tenant-gents-101',
    title: 'Gents Grand Opening Storewide Sale',
    type: 'storewide',
    discountPercent: 10,
    targetBrand: '',
    targetBarcode: '',
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    isActive: true,
    description: 'Flat 10% OFF on all purchases for store launch celebration.',
  },
  {
    id: 'disc-102',
    tenantId: 'tenant-gents-101',
    title: 'Gul Ahmed Special Festival Discount',
    type: 'brand',
    discountPercent: 15,
    targetBrand: 'Gul Ahmed',
    targetBarcode: '',
    startDate: '2026-08-10',
    endDate: '2026-08-30',
    isActive: true,
    description: '15% OFF on all Gul Ahmed unstitched lawn articles.',
  },
  {
    id: 'disc-103',
    tenantId: 'tenant-apparel-103',
    title: 'Formal Shirts Clearance Offer',
    type: 'article',
    discountPercent: 20,
    targetBrand: '',
    targetBarcode: 'APP-SHT-550301',
    startDate: '2026-08-15',
    endDate: '2026-08-31',
    isActive: true,
    description: 'Flat 20% OFF on Royal Cotton Oxford Formal Shirts.',
  },
];

export const INITIAL_SHOP_SETTINGS = {
  shopName: 'SHAAN Gents Cloth House',
  shopPhone: '+92 300 4567890',
  shopLocation: 'Azam Cloth Market, Commercial Area, Lahore, Pakistan',
  currencySymbol: 'Rs.',
  receiptFooterNote: 'Thank you for shopping at SHAAN Textiles. Returns accepted within 14 days with original receipt.',
};

export const MOCK_SALES_LOG = [
  {
    receiptNumber: 'INV-2026-9041',
    tenantId: 'tenant-gents-101',
    dateTime: '2026-07-29 14:32',
    salesman: 'Tariq Mahmood',
    salesmanId: 'u-2',
    subtotal: 15200,
    wholeSaleDiscount: 1000,
    netTotal: 14200,
    grossProfit: 7200,
    amountReceived: 15000,
    changeReturned: 800,
    paymentMethod: 'Cash',
    items: [
      { barcode: 'PAK-LAW-880101', fabric: 'Lawn (Gul Ahmed Emerald Mint)', qty: 2, unitPrice: 4200, wholesalePrice: 1850, itemDiscount: 0, total: 8400, isReturn: false, unitType: 'Suit' },
      { barcode: 'PAK-BOX-880103', fabric: 'Jacquard (J. Gift Box)', qty: 1, unitPrice: 6800, wholesalePrice: 3200, itemDiscount: 0, total: 6800, isReturn: false, unitType: 'Box' },
    ],
  },
];

export const MOCK_STOCK_UPDATES = [
  {
    id: 'stk-1',
    tenantId: 'tenant-gents-101',
    barcode: 'PAK-LAW-880101',
    itemName: 'Gul Ahmed Premium Printed Lawn (Emerald Mint)',
    type: 'Lawn',
    qtyAdded: 20,
    unitType: 'Suit',
    reason: 'Restock shipment from Azam Market Wholesaler',
    dateLogged: '2026-07-28 09:30',
    loggedBy: 'Haji Muhammad Ahmed',
    vendorId: 'ven-1',
  },
];

export const MOCK_DAMAGED_ITEMS = [
  {
    id: 'dmg-1',
    tenantId: 'tenant-gents-101',
    barcode: 'PAK-COT-880102',
    itemName: 'Pasha Superfine Latha White Bolt',
    type: 'Cotton',
    qtyRemoved: 1.5,
    unitType: 'Meter',
    reason: 'Bolt edge damage (1.5 m cut away)',
    dateLogged: '2026-07-29 11:20',
    loggedBy: 'Haji Muhammad Ahmed',
  },
];
