// mockData.js - Comprehensive Pakistani Textile & Multi-Tenant Retail Dataset

export const INITIAL_TENANTS = [
  {
    id: 'tenant-gents-101',
    name: 'NOVA MEN & WOMEN FASHION',
    tagline: 'Exclusive Men & Women Ready-to-Wear and Unstitched Fabrics',
    city: 'Jalal Pur Jattan, Gujrat',
    address: 'Main Bazar, Jalal Pur Jattan, Gujrat, Pakistan',
    phone: '+92 300 1234567',
    shopType: 'mixed_garments', // 'gents_unstitched' | 'ladies_fashion' | 'ready_made_apparel' | 'mixed_garments'
    ownerName: 'Haji Muhammad Ahmed',
    modules: {
      unstitched_fabric: true,
      ready_made_apparel: true,
      vendor_ledger: true,
      promotional_engine: true,
      analytics: true,
    },
    status: 'active',
    createdAt: '01-06-2026',
  },
  {
    id: 'tenant-ladies-102',
    name: 'Gulberg Ladies Pret & Lawn Outlet',
    tagline: 'Exclusive Designer 3-Piece & Silk Collections',
    city: 'Gulberg III, Lahore',
    address: 'Shop #8, MM Alam Road, Gulberg III, Lahore, Pakistan',
    phone: '+92 321 8899001',
    shopType: 'ladies_fashion',
    ownerName: 'Haji Muhammad Ahmed', // Multi-shop owner
    modules: {
      unstitched_fabric: true,
      ready_made_apparel: true,
      vendor_ledger: true,
      promotional_engine: true,
      analytics: true,
    },
    status: 'active',
    createdAt: '2026-07-15',
  },
  {
    id: 'tenant-apparel-103',
    name: 'Royal Threads Shirts & Trousers Hub',
    tagline: 'Ready-Made Formal Shirts, Chinos & Denim Pants',
    city: 'Tariq Road, Karachi',
    address: 'Plot #45, Commercial Area, Tariq Road, Karachi, Pakistan',
    phone: '+92 333 7766554',
    shopType: 'ready_made_apparel',
    ownerName: 'Chaudhry Rashid Tariq',
    modules: {
      unstitched_fabric: false,
      ready_made_apparel: true,
      vendor_ledger: true,
      promotional_engine: true,
      analytics: true,
    },
    status: 'active',
    createdAt: '2026-08-01',
  },
];

export const INITIAL_PRODUCTS = [
  // ==========================================
  // TENANT 1: SHAAN GENTS CLOTH HOUSE (Gents Unstitched & Ready-Made)
  // ==========================================
  {
    id: 'prod-101',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched',
    barcode: 'PAK-LAW-880101',
    fabricType: 'Lawn',
    fabricMaterial: 'Gul Ahmed Premium Printed Lawn (3-Piece)',
    fabricColor: 'Emerald Mint & Floral',
    wholesalePrice: 1850,
    retailPrice: 4200,
    initialStock: 60,
    stock: 42,
    reorderLimit: 10,
    unitType: 'Suit',
    vendorId: 'ven-1',
  },
  {
    id: 'prod-102',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched',
    barcode: 'PAK-COT-880102',
    fabricType: 'Cotton',
    fabricMaterial: 'Pasha Superfine Latha White Bolt',
    fabricColor: 'Crisp Bleached White',
    wholesalePrice: 450,
    retailPrice: 950,
    initialStock: 150,
    stock: 112.5,
    reorderLimit: 25,
    unitType: 'Meter',
    vendorId: 'ven-2',
  },
  {
    id: 'prod-103',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched',
    barcode: 'PAK-BOX-880103',
    fabricType: 'Jacquard',
    fabricMaterial: 'J. Junaid Jamshed Jacquard Gift Box Set',
    fabricColor: 'Royal Sapphire Navy',
    wholesalePrice: 3200,
    retailPrice: 6800,
    initialStock: 35,
    stock: 22,
    reorderLimit: 5,
    unitType: 'Box',
    vendorId: 'ven-3',
  },
  {
    id: 'prod-104',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched',
    barcode: 'PAK-WNW-880104',
    fabricType: 'Wash & Wear',
    fabricMaterial: 'Grace Fine Wash & Wear Gents Unstitched',
    fabricColor: 'Charcoal Slate Gray',
    wholesalePrice: 2100,
    retailPrice: 4800,
    initialStock: 50,
    stock: 31,
    reorderLimit: 8,
    unitType: 'Suit',
    vendorId: 'ven-1',
  },
  {
    id: 'prod-105',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched',
    barcode: 'PAK-KHD-880105',
    fabricType: 'Khaddar',
    fabricMaterial: 'Kamalia Handloom Pure Khaddar Suit',
    fabricColor: 'Rustic Ochre Brown',
    wholesalePrice: 1450,
    retailPrice: 3400,
    initialStock: 45,
    stock: 18,
    reorderLimit: 10,
    unitType: 'Suit',
    vendorId: 'ven-3',
  },
  {
    id: 'prod-106',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched',
    barcode: 'PAK-BSK-880106',
    fabricType: 'Silk',
    fabricMaterial: 'Pasha Pure Boski Silk 7lbs Original',
    fabricColor: 'Natural Boski Cream',
    wholesalePrice: 6500,
    retailPrice: 13500,
    initialStock: 25,
    stock: 14,
    reorderLimit: 5,
    unitType: 'Suit',
    vendorId: 'ven-2',
  },
  {
    id: 'prod-107',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched',
    barcode: 'PAK-EGY-880107',
    fabricType: 'Cotton',
    fabricMaterial: 'Dynasty Emperor Giza Cotton Roll',
    fabricColor: 'Jet Pitch Black',
    wholesalePrice: 620,
    retailPrice: 1250,
    initialStock: 180,
    stock: 135.0,
    reorderLimit: 30,
    unitType: 'Meter',
    vendorId: 'ven-5',
  },
  {
    id: 'prod-108',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched',
    barcode: 'PAK-KAR-880108',
    fabricType: 'Karandi',
    fabricMaterial: 'Sitara Winter Woolen Karandi Suit',
    fabricColor: 'Smokey Ash Grey',
    wholesalePrice: 2400,
    retailPrice: 5200,
    initialStock: 40,
    stock: 7, // Low Stock Alert
    reorderLimit: 10,
    unitType: 'Suit',
    vendorId: 'ven-4',
  },
  {
    id: 'prod-109',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched',
    barcode: 'PAK-LAT-880109',
    fabricType: 'Cotton',
    fabricMaterial: 'Al-Latif 68-68 Super White Latha',
    fabricColor: 'Bright Optical White',
    wholesalePrice: 1350,
    retailPrice: 2900,
    initialStock: 50,
    stock: 3, // Low Stock Alert
    reorderLimit: 12,
    unitType: 'Suit',
    vendorId: 'ven-1',
  },
  {
    id: 'prod-110',
    tenantId: 'tenant-gents-101',
    productType: 'unstitched',
    barcode: 'PAK-BOX-880110',
    fabricType: 'Lawn',
    fabricMaterial: 'Gul Ahmed Festive Gents Box Collection',
    fabricColor: 'Olive Bronze Gold',
    wholesalePrice: 2800,
    retailPrice: 5900,
    initialStock: 30,
    stock: 19,
    reorderLimit: 6,
    unitType: 'Box',
    vendorId: 'ven-1',
  },
  {
    id: 'prod-111',
    tenantId: 'tenant-gents-101',
    productType: 'apparel',
    barcode: 'APP-WST-880111',
    fabricType: 'Apparel',
    apparelCategory: 'Waistcoat',
    fabricMaterial: 'J. Royal Raw Silk Embroidered Waistcoat',
    fabricColor: 'Midnight Navy Blue',
    wholesalePrice: 2800,
    retailPrice: 6200,
    initialStock: 32,
    stock: 24,
    reorderLimit: 6,
    unitType: 'Piece',
    vendorId: 'ven-3',
    hasVariants: true,
    variants: [
      { id: 'var-111-1', sku: 'WST-NVY-38', size: '38 (S)', color: 'Navy Blue', stock: 6, retailPrice: 6200, wholesalePrice: 2800 },
      { id: 'var-111-2', sku: 'WST-NVY-40', size: '40 (M)', color: 'Navy Blue', stock: 8, retailPrice: 6200, wholesalePrice: 2800 },
      { id: 'var-111-3', sku: 'WST-NVY-42', size: '42 (L)', color: 'Navy Blue', stock: 7, retailPrice: 6200, wholesalePrice: 2800 },
      { id: 'var-111-4', sku: 'WST-NVY-44', size: '44 (XL)', color: 'Navy Blue', stock: 3, retailPrice: 6200, wholesalePrice: 2800 },
    ],
  },
  {
    id: 'prod-112',
    tenantId: 'tenant-gents-101',
    productType: 'apparel',
    barcode: 'APP-KRT-880112',
    fabricType: 'Apparel',
    apparelCategory: 'Kurta',
    fabricMaterial: 'Al-Karam Festive Embroidered Gents Kurta',
    fabricColor: 'Off-White Ivory',
    wholesalePrice: 1900,
    retailPrice: 4400,
    initialStock: 40,
    stock: 28,
    reorderLimit: 8,
    unitType: 'Piece',
    vendorId: 'ven-4',
    hasVariants: true,
    variants: [
      { id: 'var-112-1', sku: 'KRT-IVR-S', size: 'S (38)', color: 'Off-White', stock: 6, retailPrice: 4400, wholesalePrice: 1900 },
      { id: 'var-112-2', sku: 'KRT-IVR-M', size: 'M (40)', color: 'Off-White', stock: 10, retailPrice: 4400, wholesalePrice: 1900 },
      { id: 'var-112-3', sku: 'KRT-IVR-L', size: 'L (42)', color: 'Off-White', stock: 8, retailPrice: 4400, wholesalePrice: 1900 },
      { id: 'var-112-4', sku: 'KRT-IVR-XL', size: 'XL (44)', color: 'Off-White', stock: 4, retailPrice: 4400, wholesalePrice: 1900 },
    ],
  },

  // ==========================================
  // TENANT 2: GULBERG LADIES PRET & LAWN (Ladies Fashion)
  // ==========================================
  {
    id: 'prod-201',
    tenantId: 'tenant-ladies-102',
    productType: 'unstitched',
    barcode: 'LAD-SLK-770201',
    fabricType: 'Silk',
    fabricMaterial: 'Bareeze Pure Raw Silk Embroidered 3-Piece',
    fabricColor: 'Deep Crimson Red',
    wholesalePrice: 4200,
    retailPrice: 9500,
    initialStock: 40,
    stock: 28,
    reorderLimit: 8,
    unitType: 'Suit',
    vendorId: 'ven-2',
  },
  {
    id: 'prod-202',
    tenantId: 'tenant-ladies-102',
    productType: 'unstitched',
    barcode: 'LAD-CHF-770202',
    fabricType: 'Chiffon',
    fabricMaterial: 'Al-Karam Luxury Party Chiffon Collection',
    fabricColor: 'Pastel Rose Dust',
    wholesalePrice: 5500,
    retailPrice: 12500,
    initialStock: 25,
    stock: 14,
    reorderLimit: 5,
    unitType: 'Suit',
    vendorId: 'ven-4',
  },
  {
    id: 'prod-203',
    tenantId: 'tenant-ladies-102',
    productType: 'unstitched',
    barcode: 'LAD-VLV-770203',
    fabricType: 'Velvet',
    fabricMaterial: 'Sitara Micro-Velvet 9000 Shawl Suit',
    fabricColor: 'Royal Plum Purple',
    wholesalePrice: 3800,
    retailPrice: 8200,
    initialStock: 30,
    stock: 19,
    reorderLimit: 6,
    unitType: 'Suit',
    vendorId: 'ven-4',
  },
  {
    id: 'prod-204',
    tenantId: 'tenant-ladies-102',
    productType: 'unstitched',
    barcode: 'LAD-LAW-770204',
    fabricType: 'Lawn',
    fabricMaterial: 'Sana Safinaz Muzlin Printed 3-Piece',
    fabricColor: 'Teal Blue & Coral',
    wholesalePrice: 2200,
    retailPrice: 4950,
    initialStock: 50,
    stock: 33,
    reorderLimit: 10,
    unitType: 'Suit',
    vendorId: 'ven-1',
  },
  {
    id: 'prod-205',
    tenantId: 'tenant-ladies-102',
    productType: 'apparel',
    barcode: 'LAD-PRT-770205',
    fabricType: 'Apparel',
    apparelCategory: 'Ladies Pret',
    fabricMaterial: 'Khaadi Ready-to-Wear Embroidered 2-Piece',
    fabricColor: 'Mustard Yellow',
    wholesalePrice: 1950,
    retailPrice: 4200,
    initialStock: 36,
    stock: 25,
    reorderLimit: 6,
    unitType: 'Piece',
    vendorId: 'ven-1',
    hasVariants: true,
    variants: [
      { id: 'var-205-1', sku: 'KHD-MST-XS', size: 'XS', color: 'Mustard', stock: 4, retailPrice: 4200, wholesalePrice: 1950 },
      { id: 'var-205-2', sku: 'KHD-MST-S', size: 'S', color: 'Mustard', stock: 8, retailPrice: 4200, wholesalePrice: 1950 },
      { id: 'var-205-3', sku: 'KHD-MST-M', size: 'M', color: 'Mustard', stock: 9, retailPrice: 4200, wholesalePrice: 1950 },
      { id: 'var-205-4', sku: 'KHD-MST-L', size: 'L', color: 'Mustard', stock: 4, retailPrice: 4200, wholesalePrice: 1950 },
    ],
  },

  // ==========================================
  // TENANT 3: ROYAL THREADS SHIRTS & TROUSERS (Ready-Made Apparel)
  // ==========================================
  {
    id: 'prod-301',
    tenantId: 'tenant-apparel-103',
    productType: 'apparel',
    barcode: 'APP-SHT-550301',
    fabricType: 'Apparel',
    apparelCategory: 'Formal Shirt',
    fabricMaterial: 'Royal Cotton Oxford Slim-Fit Formal Shirt',
    fabricColor: 'Sky Blue & White',
    wholesalePrice: 1200,
    retailPrice: 2800,
    initialStock: 80,
    stock: 64,
    reorderLimit: 15,
    unitType: 'Piece',
    vendorId: 'ven-2',
    hasVariants: true,
    variants: [
      { id: 'var-301-1', sku: 'SHT-BLU-S', size: 'S (38)', color: 'Sky Blue', stock: 12, retailPrice: 2800, wholesalePrice: 1200 },
      { id: 'var-301-2', sku: 'SHT-BLU-M', size: 'M (40)', color: 'Sky Blue', stock: 18, retailPrice: 2800, wholesalePrice: 1200 },
      { id: 'var-301-3', sku: 'SHT-BLU-L', size: 'L (42)', color: 'Sky Blue', stock: 20, retailPrice: 2800, wholesalePrice: 1200 },
      { id: 'var-301-4', sku: 'SHT-BLU-XL', size: 'XL (44)', color: 'Sky Blue', stock: 14, retailPrice: 2800, wholesalePrice: 1200 },
    ],
  },
  {
    id: 'prod-302',
    tenantId: 'tenant-apparel-103',
    productType: 'apparel',
    barcode: 'APP-TRS-550302',
    fabricType: 'Apparel',
    apparelCategory: 'Dress Trouser',
    fabricMaterial: 'Executive Stretch Cotton Chino Trouser',
    fabricColor: 'Khaki Beige',
    wholesalePrice: 1400,
    retailPrice: 3200,
    initialStock: 70,
    stock: 52,
    reorderLimit: 12,
    unitType: 'Piece',
    vendorId: 'ven-3',
    hasVariants: true,
    variants: [
      { id: 'var-302-1', sku: 'TRS-KHK-30', size: 'W30 L32', color: 'Khaki Beige', stock: 10, retailPrice: 3200, wholesalePrice: 1400 },
      { id: 'var-302-2', sku: 'TRS-KHK-32', size: 'W32 L32', color: 'Khaki Beige', stock: 16, retailPrice: 3200, wholesalePrice: 1400 },
      { id: 'var-302-3', sku: 'TRS-KHK-34', size: 'W34 L32', color: 'Khaki Beige', stock: 18, retailPrice: 3200, wholesalePrice: 1400 },
      { id: 'var-302-4', sku: 'TRS-KHK-36', size: 'W36 L32', color: 'Khaki Beige', stock: 8, retailPrice: 3200, wholesalePrice: 1400 },
    ],
  },
  {
    id: 'prod-303',
    tenantId: 'tenant-apparel-103',
    productType: 'apparel',
    barcode: 'APP-PNT-550303',
    fabricType: 'Apparel',
    apparelCategory: 'Denim Jeans',
    fabricMaterial: 'Urban Raw Selvedge Slim Denim Jeans',
    fabricColor: 'Midnight Dark Indigo',
    wholesalePrice: 1600,
    retailPrice: 3900,
    initialStock: 50,
    stock: 36,
    reorderLimit: 10,
    unitType: 'Piece',
    vendorId: 'ven-3',
    hasVariants: true,
    variants: [
      { id: 'var-303-1', sku: 'JNS-IND-30', size: 'W30', color: 'Dark Indigo', stock: 8, retailPrice: 3900, wholesalePrice: 1600 },
      { id: 'var-303-2', sku: 'JNS-IND-32', size: 'W32', color: 'Dark Indigo', stock: 14, retailPrice: 3900, wholesalePrice: 1600 },
      { id: 'var-303-3', sku: 'JNS-IND-34', size: 'W34', color: 'Dark Indigo', stock: 10, retailPrice: 3900, wholesalePrice: 1600 },
      { id: 'var-303-4', sku: 'JNS-IND-36', size: 'W36', color: 'Dark Indigo', stock: 4, retailPrice: 3900, wholesalePrice: 1600 },
    ],
  },
  {
    id: 'prod-304',
    tenantId: 'tenant-apparel-103',
    productType: 'apparel',
    barcode: 'APP-POL-550304',
    fabricType: 'Apparel',
    apparelCategory: 'Polo Shirt',
    fabricMaterial: 'Classic Cotton Pique Polo Shirt',
    fabricColor: 'Forest Green',
    wholesalePrice: 950,
    retailPrice: 2200,
    initialStock: 60,
    stock: 45,
    reorderLimit: 12,
    unitType: 'Piece',
    vendorId: 'ven-2',
    hasVariants: true,
    variants: [
      { id: 'var-304-1', sku: 'POL-GRN-S', size: 'S', color: 'Forest Green', stock: 10, retailPrice: 2200, wholesalePrice: 950 },
      { id: 'var-304-2', sku: 'POL-GRN-M', size: 'M', color: 'Forest Green', stock: 15, retailPrice: 2200, wholesalePrice: 950 },
      { id: 'var-304-3', sku: 'POL-GRN-L', size: 'L', color: 'Forest Green', stock: 12, retailPrice: 2200, wholesalePrice: 950 },
      { id: 'var-304-4', sku: 'POL-GRN-XL', size: 'XL', color: 'Forest Green', stock: 8, retailPrice: 2200, wholesalePrice: 950 },
    ],
  },
];

export const INITIAL_ROLES = [
  {
    id: 'role-superadmin',
    roleName: 'Super Admin',
    description: 'Master platform administrator with authority to onboard tenants, manage subscriptions, and oversee all shop databases.',
    permissions: [
      'super_admin',
      'make_sale',
      'product_setup',
      'check_stock',
      'stock_updation',
      'vendor_ledger',
      'discounts',
      'analytics',
      'settings',
    ],
    isSystem: true,
  },
  {
    id: 'role-admin',
    roleName: 'Admin',
    description: 'Shop owner / Branch Administrator with full access to this specific shop terminal, inventory, and financial ledgers.',
    permissions: [
      'make_sale',
      'product_setup',
      'check_stock',
      'stock_updation',
      'vendor_ledger',
      'discounts',
      'analytics',
      'settings',
    ],
    isSystem: true,
  },
  {
    id: 'role-manager',
    roleName: 'Store Manager',
    description: 'Manages POS checkout, inventory restocks, vendor payments, and promotional discount campaigns.',
    permissions: [
      'make_sale',
      'product_setup',
      'check_stock',
      'stock_updation',
      'vendor_ledger',
      'discounts',
      'analytics',
    ],
    isSystem: false,
  },
  {
    id: 'role-salesman',
    roleName: 'Salesman',
    description: 'Front-desk POS checkout, stock lookup, and quick item search access.',
    permissions: ['make_sale', 'check_stock'],
    isSystem: true,
  },
  {
    id: 'role-clerk',
    roleName: 'Inventory Clerk',
    description: 'Handles product setup, barcode printing, restocks, and damage write-offs.',
    permissions: ['product_setup', 'check_stock', 'stock_updation'],
    isSystem: false,
  },
];

export const INITIAL_USERS = [
  // 1. SUPER ADMIN (SaaS Platform Master)
  {
    id: 'u-super',
    username: 'superadmin',
    password: '123',
    fullName: 'Engr. Zeeshan (Platform Super Admin)',
    role: 'Super Admin',
    tenantIds: ['tenant-gents-101', 'tenant-ladies-102', 'tenant-apparel-103'],
    isSuperAdmin: true,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
  },

  // 2. MULTI-SHOP OWNER (Owns Gents + Ladies Shops)
  {
    id: 'u-1',
    username: 'ahmed_owner',
    password: '123',
    fullName: 'Haji Muhammad Ahmed',
    role: 'Admin',
    tenantIds: ['tenant-gents-101', 'tenant-ladies-102'], // Multi-Shop Owner
    isSuperAdmin: false,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
  },

  // 3. GENTS SHOP SALESMAN
  {
    id: 'u-2',
    username: 'tariq_gents',
    password: '123',
    fullName: 'Tariq Mahmood (Gents POS)',
    role: 'Salesman',
    tenantIds: ['tenant-gents-101'],
    isSuperAdmin: false,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
  },

  // 4. LADIES SHOP SALESMAN
  {
    id: 'u-3',
    username: 'usman_ladies',
    password: '123',
    fullName: 'Usman Ghani (Ladies Pret)',
    role: 'Salesman',
    tenantIds: ['tenant-ladies-102'],
    isSuperAdmin: false,
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
  },

  // 5. APPAREL SHOP CASHIER
  {
    id: 'u-4',
    username: 'rashid_apparel',
    password: '123',
    fullName: 'Rashid Tariq (Apparel POS)',
    role: 'Admin',
    tenantIds: ['tenant-apparel-103'],
    isSuperAdmin: false,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
  },
];

export const INITIAL_VENDORS = [
  {
    id: 'ven-1',
    tenantId: 'tenant-gents-101',
    vendorName: 'Gul Ahmed Textiles Wholesalers',
    contactPerson: 'Haji Farooq Gul',
    phone: '+92 321 9876543',
    city: 'Karachi, Pakistan',
    address: 'Plot 42, SITE Industrial Area, Karachi',
    totalInvoiced: 620000,
    totalPaid: 480000,
    payments: [
      {
        id: 'pay-101',
        dateTime: '2026-08-15 11:30',
        dueDate: '2026-09-01',
        amountPaid: 250000,
        paymentMethod: 'Bank Transfer',
        referenceNote: 'Bank Al Habib Cheque #884920 - Winter lot payment',
        loggedBy: 'Haji Muhammad Ahmed',
      },
      {
        id: 'pay-102',
        dateTime: '2026-08-25 16:15',
        dueDate: '2026-09-15',
        amountPaid: 230000,
        paymentMethod: 'Cash',
        referenceNote: 'Direct cash settlement for Lawn 3-Piece shipment',
        loggedBy: 'Haji Muhammad Ahmed',
      },
    ],
    shipments: [
      {
        id: 'shp-101',
        dateTime: '2026-08-10 10:00',
        barcode: 'PAK-LAW-880101',
        itemName: 'Gul Ahmed Premium Printed Lawn (3-Piece)',
        qty: 60,
        unitType: 'Suit',
        invoiceTotal: 111000,
      },
      {
        id: 'shp-102',
        dateTime: '2026-08-20 14:30',
        barcode: 'PAK-WNW-880104',
        itemName: 'Grace Fine Wash & Wear Gents Unstitched',
        qty: 50,
        unitType: 'Suit',
        invoiceTotal: 105000,
      },
    ],
  },
  {
    id: 'ven-2',
    tenantId: 'tenant-gents-101',
    vendorName: 'Pasha Fabrics Mill Agency',
    contactPerson: 'Malik Zafar Pasha',
    phone: '+92 300 5544332',
    city: 'Faisalabad, Pakistan',
    address: 'Cloth Market Road, Ghulam Muhammad Abad, Faisalabad',
    totalInvoiced: 480000,
    totalPaid: 360000,
    payments: [
      {
        id: 'pay-201',
        dateTime: '2026-08-18 15:45',
        dueDate: '2026-09-10',
        amountPaid: 360000,
        paymentMethod: 'Bank Transfer',
        referenceNote: 'Meezan Bank Online Transfer - Boski & Latha stock',
        loggedBy: 'Haji Muhammad Ahmed',
      },
    ],
    shipments: [
      {
        id: 'shp-201',
        dateTime: '2026-08-12 12:00',
        barcode: 'PAK-COT-880102',
        itemName: 'Pasha Superfine Latha White Bolt',
        qty: 150,
        unitType: 'Meter',
        invoiceTotal: 67500,
      },
      {
        id: 'shp-202',
        dateTime: '2026-08-22 11:30',
        barcode: 'PAK-BSK-880106',
        itemName: 'Pasha Pure Boski Silk 7lbs Original',
        qty: 25,
        unitType: 'Suit',
        invoiceTotal: 162500,
      },
    ],
  },
  {
    id: 'ven-3',
    tenantId: 'tenant-apparel-103',
    vendorName: 'Denim & Garments Manufacturing Ltd',
    contactPerson: 'Khurram Shehzad',
    phone: '+92 333 4455667',
    city: 'Korangi Industrial Area, Karachi',
    address: 'Sector 15, Korangi Industrial Zone, Karachi',
    totalInvoiced: 780000,
    totalPaid: 590000,
    payments: [
      {
        id: 'pay-301',
        dateTime: '2026-08-12 12:00',
        dueDate: '2026-08-30',
        amountPaid: 350000,
        paymentMethod: 'Bank Transfer',
        referenceNote: 'Settlement for Chino trousers lot #12',
        loggedBy: 'Rashid Tariq',
      },
      {
        id: 'pay-302',
        dateTime: '2026-08-28 17:00',
        dueDate: '2026-09-20',
        amountPaid: 240000,
        paymentMethod: 'Card',
        referenceNote: 'Commercial credit card settlement',
        loggedBy: 'Rashid Tariq',
      },
    ],
    shipments: [
      {
        id: 'shp-301',
        dateTime: '2026-08-08 14:30',
        barcode: 'APP-TRS-550302',
        itemName: 'Executive Stretch Cotton Chino Trouser',
        qty: 70,
        unitType: 'Piece',
        invoiceTotal: 98000,
      },
      {
        id: 'shp-302',
        dateTime: '2026-08-20 16:00',
        barcode: 'APP-PNT-550303',
        itemName: 'Urban Raw Selvedge Slim Denim Jeans',
        qty: 50,
        unitType: 'Piece',
        invoiceTotal: 80000,
      },
    ],
  },
  {
    id: 'ven-4',
    tenantId: 'tenant-gents-101',
    vendorName: 'Sitara Textile Mills Ltd',
    contactPerson: 'Mian Tariq Sitara',
    phone: '+92 345 8877665',
    city: 'Faisalabad, Pakistan',
    address: 'Samundri Road, Industrial Triangle, Faisalabad',
    totalInvoiced: 350000,
    totalPaid: 290000,
    payments: [
      {
        id: 'pay-401',
        dateTime: '2026-08-20 10:00',
        dueDate: '2026-09-05',
        amountPaid: 290000,
        paymentMethod: 'Bank Transfer',
        referenceNote: 'Karandi & Velvet winter delivery settlement',
        loggedBy: 'Haji Muhammad Ahmed',
      },
    ],
    shipments: [
      {
        id: 'shp-401',
        dateTime: '2026-08-16 11:00',
        barcode: 'PAK-KAR-880108',
        itemName: 'Sitara Winter Woolen Karandi Suit',
        qty: 40,
        unitType: 'Suit',
        invoiceTotal: 96000,
      },
    ],
  },
  {
    id: 'ven-5',
    tenantId: 'tenant-gents-101',
    vendorName: 'Dynasty Emperor Textiles Agency',
    contactPerson: 'Kamran Dynasty',
    phone: '+92 301 9988776',
    city: 'Lahore, Pakistan',
    address: 'Main Boulevard, Gulberg II, Lahore',
    totalInvoiced: 220000,
    totalPaid: 150000,
    payments: [
      {
        id: 'pay-501',
        dateTime: '2026-08-22 14:00',
        dueDate: '2026-09-12',
        amountPaid: 150000,
        paymentMethod: 'Cash',
        referenceNote: 'Cash advance for Giza cotton bolt delivery',
        loggedBy: 'Haji Muhammad Ahmed',
      },
    ],
    shipments: [
      {
        id: 'shp-501',
        dateTime: '2026-08-19 13:00',
        barcode: 'PAK-EGY-880107',
        itemName: 'Dynasty Emperor Giza Cotton Roll',
        qty: 180,
        unitType: 'Meter',
        invoiceTotal: 111600,
      },
    ],
  },
];

export const INITIAL_PROMOTIONAL_DISCOUNTS = [
  {
    id: 'disc-101',
    tenantId: 'tenant-gents-101',
    title: 'Gents Grand Opening Storewide Sale',
    type: 'storewide',
    discountPercent: 10,
    targetBrand: '',
    targetBarcode: '',
    startDate: '2026-08-01',
    endDate: '2026-09-30',
    isActive: true,
    description: 'Flat 10% OFF across the entire store for seasonal campaign.',
  },
  {
    id: 'disc-102',
    tenantId: 'tenant-gents-101',
    title: 'Gul Ahmed Brand Festival',
    type: 'brand',
    discountPercent: 15,
    targetBrand: 'Gul Ahmed',
    targetBarcode: '',
    startDate: '2026-08-15',
    endDate: '2026-09-20',
    isActive: true,
    description: '15% OFF on all Gul Ahmed unstitched lawn & cotton articles.',
  },
  {
    id: 'disc-103',
    tenantId: 'tenant-apparel-103',
    title: 'Formal Shirts Clearance Offer',
    type: 'article',
    discountPercent: 20,
    targetBrand: '',
    targetBarcode: 'APP-SHT-550301',
    startDate: '2026-08-20',
    endDate: '2026-09-30',
    isActive: true,
    description: 'Flat 20% OFF on Royal Cotton Oxford Formal Shirts.',
  },
];

export const INITIAL_SHOP_SETTINGS = {
  shopName: 'NOVA MEN & WOMEN FASHION',
  shopPhone: '+92 300 1234567',
  shopLocation: 'Main Bazar, Jalal Pur Jattan, Gujrat, Pakistan',
  currencySymbol: 'Rs.',
  receiptFooterNote: 'Thank you for shopping at NOVA MEN & WOMEN FASHION. Exchanges accepted within 14 days with original receipt.',
};

export const MOCK_SALES_LOG = [
  {
    receiptNumber: 'INV-2026-9101',
    tenantId: 'tenant-gents-101',
    dateTime: '01-09-2026 11:20',
    salesman: 'Tariq Mahmood',
    salesmanId: 'u-2',
    subtotal: 18400,
    storewideDiscount: 1840,
    wholeSaleDiscount: 0,
    wholeSaleDiscountPercent: 0,
    netTotal: 16560,
    grossProfit: 8660,
    amountReceived: 17000,
    changeReturned: 440,
    paymentMethod: 'Cash',
    items: [
      { barcode: 'PAK-LAW-880101', fabric: 'Gul Ahmed Premium Printed Lawn (3-Piece)', qty: 2, unitPrice: 4200, wholesalePrice: 1850, itemDiscount: 0, total: 8400, isReturn: false, unitType: 'Suit' },
      { barcode: 'PAK-BSK-880106', fabric: 'Pasha Pure Boski Silk 7lbs Original', qty: 1, unitPrice: 13500, wholesalePrice: 6500, itemDiscount: 3500, total: 10000, isReturn: false, unitType: 'Suit' },
    ],
  },
  {
    receiptNumber: 'INV-2026-9102',
    tenantId: 'tenant-gents-101',
    dateTime: '01-09-2026 12:45',
    salesman: 'Tariq Mahmood',
    salesmanId: 'u-2',
    subtotal: 6800,
    storewideDiscount: 680,
    wholeSaleDiscount: 0,
    wholeSaleDiscountPercent: 0,
    netTotal: 6120,
    grossProfit: 2920,
    amountReceived: 6120,
    changeReturned: 0,
    paymentMethod: 'Card',
    items: [
      { barcode: 'PAK-BOX-880103', fabric: 'J. Junaid Jamshed Jacquard Gift Box Set', qty: 1, unitPrice: 6800, wholesalePrice: 3200, itemDiscount: 0, total: 6800, isReturn: false, unitType: 'Box' },
    ],
  },
  {
    receiptNumber: 'INV-2026-9095',
    tenantId: 'tenant-gents-101',
    dateTime: '31-08-2026 16:15',
    salesman: 'Tariq Mahmood',
    salesmanId: 'u-2',
    subtotal: 8550,
    storewideDiscount: 855,
    wholeSaleDiscount: 200,
    wholeSaleDiscountPercent: 2.5,
    netTotal: 7495,
    grossProfit: 3445,
    amountReceived: 8000,
    changeReturned: 505,
    paymentMethod: 'Cash',
    items: [
      { barcode: 'PAK-COT-880102', fabric: 'Pasha Superfine Latha White Bolt (9m)', qty: 9.0, unitPrice: 950, wholesalePrice: 450, itemDiscount: 0, total: 8550, isReturn: false, unitType: 'Meter' },
    ],
  },
  {
    receiptNumber: 'INV-2026-9080',
    tenantId: 'tenant-gents-101',
    dateTime: '29-08-2026 15:10',
    salesman: 'Tariq Mahmood',
    salesmanId: 'u-2',
    subtotal: 14400,
    storewideDiscount: 1440,
    wholeSaleDiscount: 0,
    wholeSaleDiscountPercent: 0,
    netTotal: 12960,
    grossProfit: 6660,
    amountReceived: 12960,
    changeReturned: 0,
    paymentMethod: 'Mobile Banking',
    items: [
      { barcode: 'PAK-WNW-880104', fabric: 'Grace Fine Wash & Wear Gents Unstitched', qty: 3, unitPrice: 4800, wholesalePrice: 2100, itemDiscount: 0, total: 14400, isReturn: false, unitType: 'Suit' },
    ],
  },
  {
    receiptNumber: 'INV-2026-9062',
    tenantId: 'tenant-gents-101',
    dateTime: '25-08-2026 18:30',
    salesman: 'Tariq Mahmood',
    salesmanId: 'u-2',
    subtotal: 10400,
    storewideDiscount: 1040,
    wholeSaleDiscount: 360,
    wholeSaleDiscountPercent: 3.5,
    netTotal: 9000,
    grossProfit: 4200,
    amountReceived: 10000,
    changeReturned: 1000,
    paymentMethod: 'Cash',
    items: [
      { barcode: 'PAK-KAR-880108', fabric: 'Sitara Winter Woolen Karandi Suit', qty: 2, unitPrice: 5200, wholesalePrice: 2400, itemDiscount: 0, total: 10400, isReturn: false, unitType: 'Suit' },
    ],
  },
];

export const MOCK_STOCK_UPDATES = [
  {
    id: 'stk-1',
    tenantId: 'tenant-gents-101',
    barcode: 'PAK-LAW-880101',
    itemName: 'Gul Ahmed Premium Printed Lawn (Emerald Mint)',
    type: 'Lawn',
    qtyAdded: 30,
    unitType: 'Suit',
    reason: 'Restock shipment from Gul Ahmed Wholesalers',
    dateLogged: '28-08-2026 09:30',
    loggedBy: 'Haji Muhammad Ahmed',
    vendorId: 'ven-1',
  },
  {
    id: 'stk-2',
    tenantId: 'tenant-gents-101',
    barcode: 'PAK-COT-880102',
    itemName: 'Pasha Superfine Latha White Bolt',
    type: 'Cotton',
    qtyAdded: 60,
    unitType: 'Meter',
    reason: 'Fresh roll addition from Pasha Fabrics Faisalabad',
    dateLogged: '29-08-2026 11:15',
    loggedBy: 'Haji Muhammad Ahmed',
    vendorId: 'ven-2',
  },
  {
    id: 'stk-3',
    tenantId: 'tenant-gents-101',
    barcode: 'PAK-BOX-880103',
    itemName: 'J. Junaid Jamshed Jacquard Gift Box Set',
    type: 'Jacquard',
    qtyAdded: 15,
    unitType: 'Box',
    reason: 'Eid Gift Box collection restock',
    dateLogged: '30-08-2026 14:00',
    loggedBy: 'Haji Muhammad Ahmed',
    vendorId: 'ven-3',
  },
];

export const MOCK_DAMAGED_ITEMS = [
  {
    id: 'dmg-1',
    tenantId: 'tenant-gents-101',
    barcode: 'PAK-COT-880102',
    itemName: 'Pasha Superfine Latha White Bolt',
    type: 'Cotton',
    qtyRemoved: 2.0,
    unitType: 'Meter',
    reason: 'Bolt edge weaving defect (2.0 meters cut away)',
    dateLogged: '27-08-2026 11:20',
    loggedBy: 'Tariq Mahmood',
  },
  {
    id: 'dmg-2',
    tenantId: 'tenant-gents-101',
    barcode: 'PAK-LAW-880101',
    itemName: 'Gul Ahmed Premium Printed Lawn',
    type: 'Lawn',
    qtyRemoved: 1,
    unitType: 'Suit',
    reason: 'Dye bleeding on dupatta piece during unpacking',
    dateLogged: '29-08-2026 16:40',
    loggedBy: 'Tariq Mahmood',
  },
];
