// mockData.js - Comprehensive Pakistani Retail Dataset for Shop NOVA (NOVA MEN AND WOMEN)

export const INITIAL_TENANTS = [
  {
    id: 'tenant-nova-101',
    name: 'NOVA MEN AND WOMEN',
    tagline: 'Exclusive Men & Women Ready-to-Wear, Suits & Accessories',
    city: 'Jalal Pur Jattan, Gujrat',
    address: 'Main Bazar, Jalal Pur Jattan, Gujrat, Pakistan',
    phone: '+92 300 1234567',
    shopType: 'mixed_garments',
    ownerName: 'Haji Muhammad Ahmed',
    modules: {
      ladies_suits: true,
      gents_suits: true,
      cloth_meters: false, // Confirmed: Shop NOVA does not sell cloth in meters
      ready_made_apparel: true,
      unstitched_fabric: false, // Confirmed: Shop NOVA sells ready-to-wear, stitched & packaged suits
      pin_protected_discounts: true,
      vendor_ledger: true,
      promotional_engine: true,
      analytics: true,
    },
    status: 'active',
    createdAt: '01-06-2026',
  },
  {
    id: 'tenant-testing-102',
    name: 'Testing Portal',
    tagline: 'Ladies & Gents Retail Testing Sandbox & Verification Outlet',
    city: 'Lahore, Pakistan',
    address: 'Suite #4, Model Town Commercial Area, Lahore, Pakistan',
    phone: '+92 321 8899001',
    shopType: 'mixed_garments',
    ownerName: 'QA & Testing Administrator',
    modules: {
      ladies_suits: true,
      gents_suits: true,
      cloth_meters: false,
      ready_made_apparel: true,
      unstitched_fabric: false,
      pin_protected_discounts: true,
      vendor_ledger: true,
      promotional_engine: true,
      analytics: true,
    },
    status: 'active',
    createdAt: '2026-07-15',
  },
];

export const INITIAL_PRODUCTS = [
  {
    id: 'prod-demo-1001',
    tenantId: 'tenant-nova-101',
    department: 'Ladies Pret',
    barcode: '1001',
    fabricType: 'Lawn',
    fabricMaterial: 'Khaadi Embroidered Ready-to-Wear Kurti',
    fabricColor: 'Mustard Yellow',
    wholesalePrice: 1200,
    retailPrice: 2400,
    initialStock: 25,
    stock: 25,
    reorderLimit: 5,
    unitType: 'Piece',
    vendorId: 'ven-1',
    hasVariants: false,
  },
  {
    id: 'prod-demo-1002',
    tenantId: 'tenant-nova-101',
    department: 'Gents Wear',
    barcode: '1002',
    fabricType: 'Boski',
    fabricMaterial: 'Pasha Premium Stitched Boski Gents Suit',
    fabricColor: 'Off-White / Cream',
    wholesalePrice: 3500,
    retailPrice: 6500,
    initialStock: 18,
    stock: 18,
    reorderLimit: 4,
    unitType: 'Suit',
    vendorId: 'ven-2',
    hasVariants: false,
  },
  {
    id: 'prod-demo-1003',
    tenantId: 'tenant-nova-101',
    department: 'Ladies Pret',
    barcode: '1003',
    fabricType: 'Lawn',
    fabricMaterial: 'Gul Ahmed Premium Stitched 3-Piece Lawn Pret',
    fabricColor: 'Emerald Mint & Floral',
    wholesalePrice: 2800,
    retailPrice: 5500,
    initialStock: 30,
    stock: 30,
    reorderLimit: 6,
    unitType: 'Suit',
    vendorId: 'ven-1',
    hasVariants: false,
  },
  {
    id: 'prod-demo-1004',
    tenantId: 'tenant-nova-101',
    department: 'Accessories',
    barcode: '1004',
    fabricType: 'Leather',
    fabricMaterial: 'Executive Pure Leather Bi-Fold Wallet',
    fabricColor: 'Dark Walnut Brown',
    wholesalePrice: 850,
    retailPrice: 1800,
    initialStock: 40,
    stock: 40,
    reorderLimit: 8,
    unitType: 'Item',
    vendorId: 'ven-4',
    hasVariants: false,
  },
  {
    id: 'prod-demo-1005',
    tenantId: 'tenant-nova-101',
    department: 'Gents Wear',
    barcode: '1005',
    fabricType: 'Cotton',
    fabricMaterial: 'Royal Oxford Slim-Fit Formal Cotton Shirt',
    fabricColor: 'Sky Blue',
    wholesalePrice: 1400,
    retailPrice: 2800,
    initialStock: 35,
    stock: 35,
    reorderLimit: 6,
    unitType: 'Piece',
    vendorId: 'ven-2',
    hasVariants: false,
  },
  {
    id: 'prod-demo-1006',
    tenantId: 'tenant-nova-101',
    department: 'Ladies Pret',
    barcode: '1006',
    fabricType: 'Silk',
    fabricMaterial: 'Bareeze Pure Raw Silk 3-Piece Festive Pret',
    fabricColor: 'Deep Crimson Red',
    wholesalePrice: 4500,
    retailPrice: 9500,
    initialStock: 15,
    stock: 15,
    reorderLimit: 4,
    unitType: 'Suit',
    vendorId: 'ven-1',
    hasVariants: false,
  },
];

export const INITIAL_ROLES = [
  {
    id: 'role-super',
    roleName: 'Super Admin',
    description: 'Platform Master SaaS Administrator with universal cross-tenant oversight.',
    permissions: [
      'super_admin',
      'dashboard',
      'make_sale',
      'product_setup',
      'check_stock',
      'stock_updation',
      'vendor_ledger',
      'discounts',
      'analytics',
      'settings',
    ],
    isSystem: true,
  },
  {
    id: 'role-admin',
    roleName: 'Admin',
    description: 'Store Owner / General Manager with full business terminal authority.',
    permissions: [
      'dashboard',
      'make_sale',
      'product_setup',
      'check_stock',
      'stock_updation',
      'vendor_ledger',
      'discounts',
      'analytics',
      'settings',
    ],
    isSystem: true,
  },
  {
    id: 'role-manager',
    roleName: 'Store Manager',
    description: 'Manages sales floor, stock intake, vendor transactions, and POS supervisor overrides.',
    permissions: [
      'dashboard',
      'make_sale',
      'product_setup',
      'check_stock',
      'stock_updation',
      'vendor_ledger',
      'discounts',
      'analytics',
    ],
    isSystem: false,
  },
  {
    id: 'role-salesman',
    roleName: 'Salesman',
    description: 'Front-desk POS checkout, stock lookup, and quick item search access.',
    permissions: ['make_sale', 'check_stock'],
    isSystem: true,
  },
  {
    id: 'role-clerk',
    roleName: 'Inventory Clerk',
    description: 'Handles product setup, barcode printing, restocks, and damage write-offs.',
    permissions: ['product_setup', 'check_stock', 'stock_updation'],
    isSystem: false,
  },
];

export const INITIAL_USERS = [
  // 1. MASTER ADMIN (Platform Super Admin)
  {
    id: 'u-super',
    username: 'Masteradmin',
    password: 'Admin123',
    fullName: 'Master Platform Admin',
    role: 'Super Admin',
    tenantIds: ['tenant-nova-101', 'tenant-testing-102'],
    isSuperAdmin: true,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
  },

  // 2. NOVA STORE ADMIN (NOVA MEN AND WOMEN)
  {
    id: 'u-nova',
    username: 'Nova.admin',
    password: 'Admin123',
    fullName: 'NOVA Store Administrator',
    role: 'Admin',
    tenantIds: ['tenant-nova-101'],
    isSuperAdmin: false,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
  },

  // 3. TESTING PORTAL ADMIN (Testing Sandbox)
  {
    id: 'u-testing',
    username: 'Testing.admin',
    password: 'Admin123',
    fullName: 'Testing Portal Administrator',
    role: 'Admin',
    tenantIds: ['tenant-testing-102'],
    isSuperAdmin: false,
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
  },

  // 4. FRONT-DESK CASHIER TERMINAL
  {
    id: 'u-cashier',
    username: 'Cashier1',
    password: '1234',
    fullName: 'Front-Desk Terminal Cashier',
    role: 'Salesman',
    tenantIds: ['tenant-nova-101', 'tenant-testing-102'],
    isSuperAdmin: false,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
  },
];

export const INITIAL_VENDORS = [
  {
    id: 'ven-1',
    tenantId: 'tenant-nova-101',
    vendorName: 'Gul Ahmed Textiles Wholesalers',
    contactPerson: 'Haji Farooq Gul',
    phone: '+92 321 9876543',
    city: 'Karachi, Pakistan',
    address: 'Plot 42, SITE Industrial Area, Karachi',
    totalInvoiced: 620000,
    totalPaid: 480000,
    payments: [
      {
        id: 'pay-101',
        dateTime: '2026-08-15 11:30',
        dueDate: '2026-09-01',
        amountPaid: 250000,
        paymentMethod: 'Bank Transfer',
        referenceNote: 'Bank Al Habib Cheque #884920 - Winter lot payment',
        loggedBy: 'Haji Muhammad Ahmed',
      },
      {
        id: 'pay-102',
        dateTime: '2026-08-25 16:15',
        dueDate: '2026-09-15',
        amountPaid: 230000,
        paymentMethod: 'Cash',
        referenceNote: 'Direct cash settlement for Pret 3-Piece shipment',
        loggedBy: 'Haji Muhammad Ahmed',
      },
    ],
    shipments: [
      {
        id: 'shp-101',
        dateTime: '2026-08-10 10:00',
        barcode: 'PAK-LAD-101',
        itemName: 'Gul Ahmed Premium Stitched 3-Piece Lawn Pret',
        qty: 45,
        unitType: 'Suit',
        invoiceTotal: 126000,
      },
    ],
  },
  {
    id: 'ven-2',
    tenantId: 'tenant-nova-101',
    vendorName: 'Bareeze & Royal Apparel Mills',
    contactPerson: 'Malik Zafar Bareeze',
    phone: '+92 300 5544332',
    city: 'Lahore, Pakistan',
    address: 'Gulberg Industrial Area, Lahore',
    totalInvoiced: 480000,
    totalPaid: 360000,
    payments: [
      {
        id: 'pay-201',
        dateTime: '2026-08-18 15:45',
        dueDate: '2026-09-10',
        amountPaid: 360000,
        paymentMethod: 'Bank Transfer',
        referenceNote: 'Meezan Bank Online Transfer - Silk pret & formal shirts',
        loggedBy: 'Haji Muhammad Ahmed',
      },
    ],
    shipments: [
      {
        id: 'shp-201',
        dateTime: '2026-08-12 12:00',
        barcode: 'PAK-LAD-102',
        itemName: 'Bareeze Stitched Pure Raw Silk 3-Piece',
        qty: 30,
        unitType: 'Suit',
        invoiceTotal: 135000,
      },
    ],
  },
  {
    id: 'ven-3',
    tenantId: 'tenant-nova-101',
    vendorName: 'J. Junaid Jamshed Apparel & Fragrances',
    contactPerson: 'Khurram Junaid',
    phone: '+92 333 1122334',
    city: 'Karachi, Pakistan',
    address: 'Korangi Industrial Area, Karachi',
    totalInvoiced: 520000,
    totalPaid: 450000,
    payments: [
      {
        id: 'pay-301',
        dateTime: '2026-08-10 12:00',
        dueDate: '2026-08-28',
        amountPaid: 450000,
        paymentMethod: 'Bank Transfer',
        referenceNote: 'Settlement for Kurta suits, Oudh perfumes & gift boxes',
        loggedBy: 'Haji Muhammad Ahmed',
      },
    ],
    shipments: [
      {
        id: 'shp-301',
        dateTime: '2026-08-08 14:30',
        barcode: 'PAK-GNT-201',
        itemName: 'J. Junaid Jamshed Stitched Kurta & Shalwar',
        qty: 50,
        unitType: 'Suit',
        invoiceTotal: 110000,
      },
    ],
  },
  {
    id: 'ven-4',
    tenantId: 'tenant-nova-101',
    vendorName: 'Executive Leather & Accessories Ltd',
    contactPerson: 'Mian Tariq Leather',
    phone: '+92 345 8877665',
    city: 'Sialkot, Pakistan',
    address: 'Small Industrial Estate, Sialkot',
    totalInvoiced: 210000,
    totalPaid: 180000,
    payments: [
      {
        id: 'pay-401',
        dateTime: '2026-08-20 10:00',
        dueDate: '2026-09-05',
        amountPaid: 180000,
        paymentMethod: 'Bank Transfer',
        referenceNote: 'Wallets & reversible belts settlement',
        loggedBy: 'Haji Muhammad Ahmed',
      },
    ],
    shipments: [
      {
        id: 'shp-401',
        dateTime: '2026-08-16 11:00',
        barcode: 'ACC-WLT-990402',
        itemName: 'Executive Full-Grain Leather Bi-Fold Wallet',
        qty: 50,
        unitType: 'Item',
        invoiceTotal: 42500,
      },
    ],
  },
];

export const INITIAL_PROMOTIONAL_DISCOUNTS = [
  {
    id: 'disc-101',
    tenantId: 'tenant-nova-101',
    title: 'Grand Opening Storewide Sale',
    type: 'storewide',
    discountPercent: 10,
    targetBrand: '',
    targetBarcode: '',
    startDate: '2026-08-01',
    endDate: '2026-09-30',
    isActive: true,
    description: 'Flat 10% OFF across the entire store for seasonal campaign.',
  },
  {
    id: 'disc-102',
    tenantId: 'tenant-nova-101',
    title: 'Gul Ahmed Brand Festival',
    type: 'brand',
    discountPercent: 15,
    targetBrand: 'Gul Ahmed',
    targetBarcode: '',
    startDate: '2026-08-15',
    endDate: '2026-09-20',
    isActive: true,
    description: '15% OFF on all Gul Ahmed Pret & Gift Collections.',
  },
  {
    id: 'disc-103',
    tenantId: 'tenant-nova-101',
    title: 'Formal Shirts Clearance Offer',
    type: 'article',
    discountPercent: 20,
    targetBrand: '',
    targetBarcode: 'APP-SHT-550301',
    startDate: '2026-08-20',
    endDate: '2026-09-30',
    isActive: true,
    description: 'Flat 20% OFF on Royal Cotton Oxford Formal Shirts.',
  },
];

export const INITIAL_PRINTER_SETTINGS = {
  receiptPrinter: 'BIXOLON SRP-Q302',
  labelPrinter: 'ZDesigner iMZ220 (ZPL)',
  receiptPaperWidth: '75mm',
  labelSize: '50x30mm',
  printMethod: 'thermal_transfer',
  autoPrintReceipt: true,
  autoPrintLabel: false,
  silentPrinting: true,
  showReceiptModal: true,
};

export const INITIAL_SHOP_SETTINGS = {
  shopName: 'NOVA MEN AND WOMEN',
  shopPhone: '+92 300 1234567',
  shopLocation: 'Main Bazar, Jalal Pur Jattan, Gujrat, Pakistan',
  currencySymbol: 'Rs.',
  taxNumber: 'NTN-8492048-2',
  discountPin: '1234',
  receiptFooterNote: 'Thank you for shopping at NOVA MEN AND WOMEN. Exchanges accepted within 14 days with original receipt.',
  receiptPrinter: 'BIXOLON SRP-Q302',
  labelPrinter: 'ZDesigner iMZ220 (ZPL)',
  receiptPaperWidth: '75mm',
  labelSize: '50x30mm',
  printMethod: 'thermal_transfer',
  autoPrintReceipt: true,
  silentPrinting: true,
};

export const INITIAL_PRODUCT_TEMPLATES = [
  {
    id: 'tmpl-1',
    name: 'Formal & Casual Shirt',
    department: 'Gents Wear',
    unitType: 'Piece',
    availableSizes: ['S (38)', 'M (40)', 'L (42)', 'XL (44)', 'XXL (46)'],
    availableFabrics: ['Cotton Oxford', 'Linen', 'Egyptian Giza Cotton', 'Polyester Blend'],
    fits: ['Slim Fit', 'Regular Fit', 'Classic'],
  },
  {
    id: 'tmpl-2',
    name: 'Dress Pants & Chinos',
    department: 'Gents Wear',
    unitType: 'Piece',
    availableSizes: ['W30 L32', 'W32 L32', 'W34 L32', 'W36 L32', 'W38 L32', 'W40 L32'],
    availableFabrics: ['Stretch Cotton Twill', 'Wool Blend', 'Raw Denim', 'Tropical Poly-Viscose'],
    fits: ['Slim Fit', 'Straight Fit', 'Tailored Fit'],
  },
  {
    id: 'tmpl-3',
    name: 'Gents Waistcoat & Blazer',
    department: 'Gents Wear',
    unitType: 'Piece',
    availableSizes: ['36', '38', '40', '42', '44', '46'],
    availableFabrics: ['Raw Silk', 'Velvet', 'Jacquard', 'Tropical Wool'],
    fits: ['Slim Fit', 'Standard'],
  },
  {
    id: 'tmpl-4',
    name: 'Gents Kurta & Shalwar Kameez',
    department: 'Gents Wear',
    unitType: 'Suit',
    availableSizes: ['S', 'M', 'L', 'XL'],
    availableFabrics: ['Cotton Latha', 'Wash & Wear', 'Karandi', 'Silk'],
    fits: ['Regular', 'Smart Fit'],
  },
  {
    id: 'tmpl-5',
    name: 'Ladies 3-Piece Stitched Pret',
    department: 'Ladies Pret',
    unitType: 'Suit',
    availableSizes: ['XS', 'S', 'M', 'L', 'XL'],
    availableFabrics: ['Premium Printed Lawn', 'Chiffon Embroidered', 'Raw Silk', 'Jacquard'],
    fits: ['Standard', 'A-Line', 'Frock'],
  },
  {
    id: 'tmpl-6',
    name: 'Suit in Gift Box (Packaged)',
    department: 'Packaged Gift Boxes',
    unitType: 'Box',
    availableSizes: ['Standard Gift Box', 'Premium Executive Set Box'],
    availableFabrics: ['Pure Silk', 'Pasha Latha', 'Gul Ahmed Jacquard'],
    fits: ['Box Packaging'],
  },
  {
    id: 'tmpl-7',
    name: 'Luxury Fragrance & Leather Accessories',
    department: 'Accessories',
    unitType: 'Item',
    availableSizes: ['Standard', '50ml', '100ml'],
    availableFabrics: ['Full-Grain Leather', 'French Crystal Bottle'],
    fits: ['Accessories'],
  },
];

export const INITIAL_DAY_SETTLEMENTS = [
  {
    id: 'set-2026-0901',
    date: '01-09-2026',
    closedAt: '01-09-2026 21:30',
    closedBy: 'NOVA Store Administrator (Admin)',
    cashierName: 'Front-Desk Terminal Cashier',
    expectedCash: 34500,
    actualCash: 34500,
    discrepancy: 0,
    digitalSales: 28000,
    totalSales: 62500,
    status: 'balanced',
    reasonNote: 'Cashier drawer balanced perfectly with counter register.',
  },
];

export const MOCK_SALES_LOG = [
  {
    receiptNumber: 'INV-2026-9201',
    tenantId: 'tenant-nova-101',
    dateTime: '21-09-2026 14:30',
    salesman: 'Front-Desk Terminal Cashier',
    salesmanId: 'u-cashier',
    subtotal: 2400,
    storewideDiscount: 0,
    wholeSaleDiscount: 0,
    wholeSaleDiscountPercent: 0,
    netTotal: 2400,
    grossProfit: 1200,
    amountReceived: 3000,
    changeReturned: 600,
    paymentMethod: 'Cash',
    items: [
      { barcode: '1001', fabric: 'Khaadi Embroidered Ready-to-Wear Kurti', qty: 1, unitPrice: 2400, wholesalePrice: 1200, itemDiscount: 0, total: 2400, isReturn: false, unitType: 'Piece', department: 'Ladies Pret' },
    ],
  },
  {
    receiptNumber: 'INV-2026-9202',
    tenantId: 'tenant-nova-101',
    dateTime: '21-09-2026 16:15',
    salesman: 'Front-Desk Terminal Cashier',
    salesmanId: 'u-cashier',
    subtotal: 6500,
    storewideDiscount: 0,
    wholeSaleDiscount: 0,
    wholeSaleDiscountPercent: 0,
    netTotal: 6500,
    grossProfit: 3000,
    amountReceived: 6500,
    changeReturned: 0,
    paymentMethod: 'Card',
    items: [
      { barcode: '1002', fabric: 'Pasha Premium Stitched Boski Gents Suit', qty: 1, unitPrice: 6500, wholesalePrice: 3500, itemDiscount: 0, total: 6500, isReturn: false, unitType: 'Suit', department: 'Gents Wear' },
    ],
  },
  {
    receiptNumber: 'INV-2026-9203',
    tenantId: 'tenant-nova-101',
    dateTime: '21-09-2026 18:00',
    salesman: 'Front-Desk Terminal Cashier',
    salesmanId: 'u-cashier',
    subtotal: 4600,
    storewideDiscount: 0,
    wholeSaleDiscount: 0,
    wholeSaleDiscountPercent: 0,
    netTotal: 4600,
    grossProfit: 2350,
    amountReceived: 5000,
    changeReturned: 400,
    paymentMethod: 'Cash',
    items: [
      { barcode: '1005', fabric: 'Royal Oxford Slim-Fit Formal Cotton Shirt', qty: 1, unitPrice: 2800, wholesalePrice: 1400, itemDiscount: 0, total: 2800, isReturn: false, unitType: 'Piece', department: 'Gents Wear' },
      { barcode: '1004', fabric: 'Executive Pure Leather Bi-Fold Wallet', qty: 1, unitPrice: 1800, wholesalePrice: 850, itemDiscount: 0, total: 1800, isReturn: false, unitType: 'Item', department: 'Accessories' },
    ],
  },
  {
    receiptNumber: 'INV-2026-9204',
    tenantId: 'tenant-nova-101',
    dateTime: '21-09-2026 20:10',
    salesman: 'Front-Desk Terminal Cashier',
    salesmanId: 'u-cashier',
    subtotal: 5500,
    storewideDiscount: 0,
    wholeSaleDiscount: 0,
    wholeSaleDiscountPercent: 0,
    netTotal: 5500,
    grossProfit: 2700,
    amountReceived: 5500,
    changeReturned: 0,
    paymentMethod: 'Mobile Banking',
    items: [
      { barcode: '1003', fabric: 'Gul Ahmed Premium Stitched 3-Piece Lawn Pret', qty: 1, unitPrice: 5500, wholesalePrice: 2800, itemDiscount: 0, total: 5500, isReturn: false, unitType: 'Suit', department: 'Ladies Pret' },
    ],
  },
];

export const MOCK_STOCK_UPDATES = [
  {
    id: 'stk-1',
    tenantId: 'tenant-nova-101',
    barcode: 'PAK-LAD-101',
    itemName: 'Gul Ahmed Premium Stitched 3-Piece Lawn Pret',
    type: 'Lawn',
    qtyAdded: 25,
    unitType: 'Suit',
    reason: 'Restock shipment from Gul Ahmed Wholesalers',
    dateLogged: '28-08-2026 09:30',
    loggedBy: 'Haji Muhammad Ahmed',
    vendorId: 'ven-1',
  },
  {
    id: 'stk-2',
    tenantId: 'tenant-nova-101',
    barcode: 'PAK-GNT-201',
    itemName: 'J. Junaid Jamshed Stitched Kurta & Shalwar',
    type: 'Cotton',
    qtyAdded: 30,
    unitType: 'Suit',
    reason: 'Fresh Eid stock delivery from J. Agency',
    dateLogged: '29-08-2026 11:15',
    loggedBy: 'Haji Muhammad Ahmed',
    vendorId: 'ven-3',
  },
  {
    id: 'stk-3',
    tenantId: 'tenant-nova-101',
    barcode: 'PAK-BOX-880103',
    itemName: 'J. Junaid Jamshed Jacquard Gift Box Set',
    type: 'Jacquard',
    qtyAdded: 15,
    unitType: 'Box',
    reason: 'Eid Gift Box collection restock',
    dateLogged: '30-08-2026 14:00',
    loggedBy: 'Haji Muhammad Ahmed',
    vendorId: 'ven-3',
  },
];

export const MOCK_DAMAGED_ITEMS = [
  {
    id: 'dmg-1',
    tenantId: 'tenant-nova-101',
    barcode: 'APP-SHT-550301',
    itemName: 'Royal Cotton Oxford Slim-Fit Formal Shirt',
    type: 'Cotton',
    qtyRemoved: 1,
    unitType: 'Piece',
    reason: 'Cuff stitching fault detected during unboxing',
    dateLogged: '27-08-2026 11:20',
    loggedBy: 'Front-Desk Terminal Cashier',
  },
  {
    id: 'dmg-2',
    tenantId: 'tenant-nova-101',
    barcode: 'PAK-LAD-101',
    itemName: 'Gul Ahmed Premium Stitched 3-Piece Lawn Pret',
    type: 'Lawn',
    qtyRemoved: 1,
    unitType: 'Suit',
    reason: 'Button missing on front neckline piece',
    dateLogged: '29-08-2026 16:40',
    loggedBy: 'Front-Desk Terminal Cashier',
  },
];
